# Security check for the go module file
name: Security checks

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate go modules
        run: |
          cd pkg
          npm install snyk@latest -g
          go mod graph
          snyk test
